---
name: eliud_core_create
description: Eliud core create is the core create eliud package which includes core classes for wizards and editors. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_core
version: 1.1.5+7
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  eliud_core_model: 1.0.0

  flutter:
    sdk: flutter
dependency_overrides:
  eliud_core_model:
    path: ../eliud_core_model
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
